### PR TITLE
Fix error code

### LINKED ISSUE #343: Proposed error code changes
If `ab-p-archive-056` is supposed to return `err:XC0085`, then I assert that `ab-p-archive-057` must also.

### PR DESCRIPTION
**Pull request by ndw**
Fix #343 

I don't expect this to be controversial.

### CODE REVIEW

**Comment by ndw** [comment]
I'm confused.

The heart of `ab-p-archive-056` is this step:

```
            <p:archive>
               <p:with-input port="source"><p:empty /></p:with-input>
               <p:with-input port="manifest"><p:empty /></p:with-input>
               <p:with-input port="archive">
                  <p:inline content-type="text/plain">This is no zip.</p:inline>
               </p:with-input>
            </p:archive>
```

the heart of `ab-p-archve-057` is this step:

```
            <p:archive format="zip">
               <p:with-input port="source"><p:empty /></p:with-input>
               <p:with-input port="manifest"><p:empty /></p:with-input>
               <p:with-input port="archive">
                  <p:inline content-type="text/plain">This is no zip.</p:inline>
               </p:with-input>
            </p:archive>
```

The default value for the `format` attribute on `p:archive` is "zip". So I don't see how these two tests can possibly be expected to give different results.

**Comment by xml-project** [comment]
Right, but 056 does not have a `format` option and this makes the difference:

`format` present and document is not format -> XC0081
no `format` present and document not processable -> XC0085

I have not invented this distinction but I think the idea is this: Suppose I support "zip" and another archive type "x". If `format = 'zip'`, but document is of type 'a', XC0081 has to be raised. XC0085 is not allowed, because I support 'a'.
What did I miss?

**Comment by ndw** [comment]
I'm still confused. The *default value* of the `format` attribute is "zip". And the format attribute is not optional. AFAICT, it is not possible for the step to run with a format attribute that is "not present".

**Comment by xml-project** [comment]
> And the format attribute is not optional.

To my reading **it is** optional:

<p:option name="format" as="xs:QName" select="'zip'"/> 

What did I miss?

**Comment by ndw** [comment]
It's optional *for the pipeline author*. But if the author doesn't provide a value, the default value is "zip". So *from the perspective of the step implementation*, the format attribute always has a value. It can't not have a value.

What am I missing?

**Comment by xml-project** [comment]
Now I see your point. You are right.
But does the distinction between the two errors make any sense? I took it to mean, that we have to make a distinction where 'zip' is given and 'zip' is only assumed, but not state it.

We should talk about this at tomorrows call, so the inventer of the distinction can enlight us.

**Comment by ndw** [comment]
I'd be happy to combine them into a single code. I struggled to work out which one to raise and there are a few places where I have extra tests to raise one when the other would have been raised a moment later.

**Comment by xml-project** [comment]
Same here!

**Comment by ndw** [comment]
Subsumed by #352

**Pull request closed without merging**
