### PR TITLE
Adding platform attribute to t:test

### PR DESCRIPTION
**Pull request by xml-project**

### CODE REVIEW

**Comment by xml-project** [comment]
@ndw any opinion on that?

**Comment by xml-project** [comment]
@ndw Yes, we could do that. I wanted it to be as open as possible, e.g. for my upcoming implementation of XProc 3.0 on a Rasberry PI ;-))

**Comment by ndw** [comment]
We can always add more. What I'd like to avoid is `platform="windows"` on one test and `platform="Windows"` on another test and different test runs getting weirdly different results.

**Comment by gimsieke** [comment]
Raspberry Pi OS is nothing but Linux, innit? 
The question is whether there are differences between Mac OS X (and newer) and Linux for all practical purposes? If it weren’t for the trademarks, we could call it 'Unix' or 'POSIX' (although Linux is neither, strictly speaking).

**Comment by xml-project** [comment]
@gimsieke You missed the point of this PR.

**Pull request merged**
